### ISSUE TITLE
Cannot read property 'hostedBy' of undefined 

### ISSUE THREAD

**Issue by Botreddai** [ZeroDiscord/GiveawayBot#14]
![20211021_092243](https://user-images.githubusercontent.com/79804219/138276496-343be50f-b69e-4251-9fc7-0076f8d09bcf.jpg)

**Comment by ZeroDiscord** [comment]
This repository has been depreciated, take a look at the new one [here](https://GitHub.com/ZeroDiscord/Giveaway)
